version: '3.8'

services:
  backend:
    build: ./backend
    env_file:
      - .env.prod
    environment:
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
      - MONGO_DB=${MONGO_DB}
      - MONGO_URI_TEMPLATE=${MONGO_URI_TEMPLATE}
      - ORV_API_LINK=${ORV_API_LINK}
    expose:
      - "3001"

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL}
    env_file:
      - .env.prod
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    volumes:
      - frontend-build:/app/build
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - frontend-build:/usr/share/nginx/html:ro
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

volumes:
  frontend-build:
