version: '3.8'

services:
  backend:
    build: ./backend
    env_file:
      - .env.prod
    environment:
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
      - MONGO_DB=${MONGO_DB}
      - MONGO_URI_TEMPLATE=${MONGO_URI_TEMPLATE}
      - ORV_API_LINK=${ORV_API_LINK}
    expose:
      - "3001"
    volumes:
      - ./backend/images:/backend/images
    networks:
      - app-network


  frontend:
    build: ./frontend
    env_file:
      - .env.prod
    depends_on:
      - backend
    expose:
      - "3000"
    ports:
      - "3000:3000"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - ./nginx/privkey.pem:/etc/ssl/private/privkey.pem:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network


volumes:
  frontend-build:

networks:
  app-network: